package day0530.oop;

class UserExceptionTest{
	public void test1(String[] n) throws UserException{
		System.out.println("Test1");
	if(n.length < 1)
		throw new UserException("암것도 읎네"); //강제 exception 발생
	else
		throw new UserException("최종 예선",703);// 강제 exception 발생

	}
	public static void main(String[] args) {
		UserExceptionTest ut = new UserExceptionTest();
		try {
			ut.test1(args);
		}catch(UserException ue) {
			//System.out.println(ue.getMessage());
			ue.printStackTrace();	
		}
}
}
